const escapeHtml = (value) => String(value ?? "").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[character]));
const layout = (title, content) => `<!doctype html><html><body style="margin:0;background:#f6f2f4;font-family:Arial,sans-serif;color:#322c35"><div style="max-width:600px;margin:auto;padding:36px 20px"><div style="background:#fff;border-radius:18px;padding:34px"><p style="color:#755c7b;font-size:12px;letter-spacing:2px;text-transform:uppercase">Virtuosa</p><h1 style="font-family:Georgia,serif;font-weight:400">${escapeHtml(title)}</h1>${content}</div><p style="text-align:center;color:#8d838b;font-size:12px">Moda y belleza para expresarte.</p></div></body></html>`;
const sendEmail = async ({ to, subject, html, idempotencyKey }) => {
    if (!process.env.RESEND_API_KEY || !to) return { skipped: true };
    const response = await fetch("https://api.resend.com/emails", { method: "POST", headers: { Authorization: `Bearer ${process.env.RESEND_API_KEY}`, "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, body: JSON.stringify({ from: process.env.EMAIL_FROM || "Virtuosa <onboarding@resend.dev>", to: [to], subject, html }) });
    if (!response.ok) throw new Error(`Resend respondió ${response.status}`);
    return response.json();
};
const sendOrderConfirmation = (order) => sendEmail({ to: order.customer_email, subject: `Recibimos tu pedido ${order.reference}`, idempotencyKey: `order-confirmation-${order.id}`, html: layout("¡Gracias por tu compra!", `<p>Hola ${escapeHtml(order.customer_name)}, recibimos tu pedido.</p><p><strong>Referencia:</strong> ${escapeHtml(order.reference)}<br><strong>Total:</strong> $${Number(order.total).toLocaleString("es-CO")}</p><p>Puedes consultar su avance desde “Seguir mi pedido”.</p>`) });
const sendOrderStatus = (order) => sendEmail({ to: order.customer_email, subject: `Tu pedido ${order.reference} cambió de estado`, idempotencyKey: `order-status-${order.id}-${order.status}`, html: layout("Actualización de tu pedido", `<p>Hola ${escapeHtml(order.customer_name)}, tu pedido <strong>${escapeHtml(order.reference)}</strong> ahora está en estado <strong>${escapeHtml(order.status)}</strong>.</p>`) });
const sendPasswordReset = (user, resetUrl) => sendEmail({ to: user.email, subject: "Restablece tu acceso a Virtuosa", idempotencyKey: `password-reset-${user.id}-${Date.now()}`, html: layout("Restablecer contraseña", `<p>Hola ${escapeHtml(user.name)}, recibimos una solicitud para cambiar tu contraseña.</p><p><a style="display:inline-block;padding:14px 20px;border-radius:10px;background:#352d35;color:#fff;text-decoration:none" href="${escapeHtml(resetUrl)}">Crear nueva contraseña</a></p><p>El enlace vence en 30 minutos.</p>`) });
module.exports = { sendOrderConfirmation, sendOrderStatus, sendPasswordReset };
